### ISSUE TITLE
2018 Status

### ISSUE THREAD

**Issue by nightpool** [WICG/web-share-target#37]
What's the current status of the Web Share Target proposal? I'm working with one of the current implementors of Web Share Target (https://github.com/tootsuite/mastodon/issues/5850) to enhance our current PWA and i'd like to share our experiences and feedback from users 

Mastodon is an open-source, distributed microblogging platform, which many users use PWA provided by their individual servers (mastodon.social, pawoo.net, witches.town) to access. Across the entire network we have over 50,000 weekly active users. Unfortunately we don't have any network-wide statistics on what applications people use, but anecdotally it seems like the majority of mobile users use dedicated apps, but with a fast-growing segment using mastodon in their mobile browsers / as a progressive web app.

Here are some of the issues we've identified so far:

 - [ ] It's unclear how to enable or activate this feature, so not many users have tested it
 - [x] It's hard for users to discover that this feature exists and is supported by Mastodon, so they don't think to select "share" when they 
 - [ ] It doesn't support sharing many of the types of media Mastodon allows you to post, like photos and images, so it's functionality, once discovered and enabled, is very limited and may not seem useful to many users.

Do you have any ideas about ways our implementation or the spec could address these issues? Would love to hear about your experiences here or possible steps forward for us.

**Comment by mgiuca** [comment]
Hi @nightpool 

Thanks and it's great to see that Mastodon has implemented WST. I just tried it out on Android Chrome Canary and it works great.

WST standards is one of our priorities for 2018. Right now we are going through the W3C TAG review process (you can follow along at w3ctag/design-reviews#221) and we have a meeting scheduled for next week.

> It's unclear how to enable or activate this feature, so not many users have tested it
> It's hard for users to discover that this feature exists and is supported by Mastodon, so they don't think to select "share" when they

This necessarily has to be user-agent-specific. In Chrome, I think it's natural to auto-register it when the user installs the app, which is what we've done on Android. Since Mastodon prompts the user to install the app when you sign in, that in effect is also activating the WST feature and I think it's fairly discoverable from there.

(Obviously not many users will use Chrome Dev/Canary, but this will be solved when we push it out to stable, once standards are further down the line.)

> It doesn't support sharing many of the types of media Mastodon allows you to post, like photos and images, so it's functionality, once discovered and enabled, is very limited and may not seem useful to many users.

Yep, we're looking at sharing images and other data in a later extension to the API: #29

I'll close this ticket as it isn't really an actionable issue, but it's great to see support from the web community!
