### ISSUE TITLE
How to validate a share_target url ?

### ISSUE THREAD

**Issue by xfalcox** [WICG/web-share-target#38]
I can't get my webapp to show as a share target in the current Chrome Canary.

Here is the manifest:

https://meta.discourse.org/manifest.json

**Comment by mgiuca** [comment]
Hi, it sounds like you have a Chrome issue, not an issue with the web standard. These should be reported to https://crbug.com/new.

Though I wonder if you've installed the app as a WebAPK (requires that it satisfies the [PWA Checklist](https://developers.google.com/web/progressive-web-apps/checklist)). Chrome for Android only lets installed PWAs register as share targets.

**Comment by mgiuca** [comment]
Closing the issue. If it is still a problem, please report on https://crbug.com/new.

**Comment by mgiuca** [comment]
I was wondering why you had `\u0026` and `%0A%0A` in there. `'\u0026'` and `'&'` are exactly equivalent in JSON so that will be the same. `'%0A'` and `'\n'` should be equivalent per the [URL standard](https://url.spec.whatwg.org/#c0-control-percent-encode-set). So that encoding that Rails is doing is fine, though it shouldn't be necessary.

I'm not sure why you want newlines in your URL. If you're trying to create a POST-style HTTP request body (by inserting two newlines), that won't work. This will just make a GET request with "%0A%0A" in the request header.

I don't see any reason, though, why this wouldn't be accepted as a valid web share target URL.

**Comment by xfalcox** [comment]
> I'm not sure why you want newlines in your URL. If you're trying to create a POST-style HTTP request body (by inserting two newlines), that won't work. This will just make a GET request with "%0A%0A" in the request header.

This is a our URL at Discourse to create a new topic in Discourse:

https://meta.discourse.org/new-topic?title=title&body=text%0A%0Aurl

will produce:

![image](https://user-images.githubusercontent.com/1385470/39219070-c33dc5fe-47fe-11e8-9e85-08d0beb4e2af.png)

I tested a sharing a bunch of stuff from different Android apps, and we don't always get `url` and `text` so I'm just adding both to our post text area separated by line breaks to help the user compose his topic.

However it's not being correctly detected by current Chrome Canary in the Android and I was afraid that one of those special characters were infringing the spec.

**Comment by mgiuca** [comment]
Ahh I see, sorry I completely missed the fact that the URL was part of the "body" parameter (I thought you were trying to do some weird HTTP thing). That makes sense and _should_ work. Can you file a bug in https://crbug.com/new, and I'll try to look at it.

Note: We've [recently discussed](https://github.com/w3ctag/design-reviews/issues/221) changing this to a new syntax which would **not** allow you to compose a parameter like that (you would only be able to set each query parameter to one of the share fields). I've written an analysis of this on a comment on that issue.
