### ISSUE TITLE
Migration to WebApps WG: Implementor interest?

### ISSUE THREAD

**Issue by LJWatson** [WICG/web-share-target#73]
This specification has been proposed for migration to the [WebApps WG](https://w3c.github.io/charter-drafts/webapps-2019) (which is expected to partly replace the WebPlat WG). For this to happen, we need expressions of interest/intent to commit from at least two implementors.

Please let us know if you plan to implement this specification, or if you can point to any publicly documented expressions of interest from implementors.

The draft WebApps charter will go to the Advisory Committee (AC) within the next two or three weeks, so quick responses may make the difference.

@Chaals @marcoscaceres

**Comment by ewilligers** [comment]
Chrome's implementation is in progress - [Intent to Implement](https://groups.google.com/a/chromium.org/d/msg/chromium-dev/HdrXCCQ9UXo/9HUFqUymCgAJ).

**Comment by marcoscaceres** [comment]
Sorry, wrong repo 😣 I'm deleting my comment above.

**Comment by marcoscaceres** [comment]
Mozilla doesn't plan to implement this specification at the moment, but we would like to see Web Share Target continue  be standardized together with the Web Share API. We feel that Web Share without Web Share Target wouldn't be ideal, because it risks further centralization and unfair preference to particular silos. 

Thus, we are supportive of it being part of the Web Apps WG charter and Tantek has agreed to provide feedback from and review from Mozilla's side during the spec's development - once the spec moves over (I can also review stuff if needed).

**Comment by marcoscaceres** [comment]
Closing again... will spin up a new issue.
